### ISSUE TITLE
Users can submit applications for dogs

### ISSUE THREAD

**Issue by nuffQuantumSayd** [nuffQuantumSayd/AnimalRescueWebsite#13]
Users will be able to click on a dog card application button and be directed to an application that they can fill out and submit.
- [x] #30
- [x] #32
- [x] #35

**Comment by nuffQuantumSayd** [comment]
Users will be able to click on a dog card application button and be directed to an application that they can fill out and submit.
- [ ] Create an "Apply" Action in the Controller
- [ ] Create an Application Form View
- [ ] Create a "SubmitApplication" Action
- [ ] Create a Database Model for applications
- [ ] Set Up a Database Context
- [ ] Submit the Application
- [ ] Database Migrations
- [ ] ApplicationSubmitted View

**Comment by nuffQuantumSayd** [comment]
MVC basics and Documentation
https://learn.microsoft.com/en-us/aspnet/mvc/overview/getting-started/

Foreign key data annotations
https://learn.microsoft.com/en-us/ef/core/modeling/relationships/mapping-attributes
